<!DOCTYPE html>
<html>
<head>
	<title> Reminder | راحت بخاطر بسپار !</title>
    <meta charset="utf-8">
    
    <!-- Css Files Include -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <!-- Javascript Files Include -->
</head>
<body>
  <div class="container">
	<div class="header">
    	<div class="nav-logo nav-section">Reminder</div>
        <div class="nav-search nav-section">
        	<form action="" method="">
            	<div class="search"><input type="search" id="search" placeholder="search ..."></div>
            </form>
        </div>
        <div class="nav-section nav-list">
        	<ul>
            	<li><a href="">Home</a></li>
                <li><a href="">Newsfeed</a></li>
                <li><a href="">Timeline</a></li>
                <li><a href="">Allpage</a></li>
                <li><a href="">Contant</a></li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
    <div class="home-body">
    	<div class="about">
        	<h2> Remind all your data !!! </h2>
            <br>
            <p> Reminder is a web application software that helps you remind your all data like 
               words , texts , dates and others base on scientific rules.
            </p>
            <p>Why are you waiting for? Sign up now!</p>
            <button class="home-btn"> Learn More </button>
        </div>
        <div class="form-btn">
        <div class="fb1">log in</div>
        <div class="fb1" >Register</div>
        </div>
    <div class="forms">
     <span class="brand">Reminder</span>
        <h2> Log in </h2>
        <p> log in to use out wonderfull features </p>
       
        	<form class="" id="" method="post">
            
                <input type="text" id="email2" placeholder="email or username"/>
                <input type="text" id="password2" placeholder="Password"/>
               
                <a href="">Do not habe an account??</a> 
                <button class="home-btn">Log in</button>
            </form>
            <div class="social-media">
            	
            </div>
        </div>
    </div>
    
  </div>  
</body>
</html>